// Popular icons from Lucide that match ClickUp's style
export const POPULAR_ICONS = [
    "Rocket", "Star", "Heart", "Zap", "Target", "TrendingUp", "Award",
    "Briefcase", "Calendar", "Clock", "Users", "User", "Mail", "Phone",
    "Home", "Building", "Store", "ShoppingCart", "Package", "Truck",
    "DollarSign", "CreditCard", "Wallet", "PiggyBank", "TrendingDown",
    "BarChart", "PieChart", "Activity", "Database", "Server",
    "Code", "Terminal", "Cpu", "HardDrive", "Wifi",
    "Globe", "Map", "MapPin", "Navigation", "Compass",
    "Camera", "Image", "Film", "Music", "Headphones",
    "Book", "BookOpen", "FileText", "File", "Folder",
    "Inbox", "Archive", "Trash", "Edit", "Save",
    "Download", "Upload", "Send", "Share", "Link",
    "Bell", "BellOff", "Flag", "Bookmark", "Tag",
    "Settings", "Tool", "Wrench", "Hammer", "Scissors",
    "Palette", "Brush", "Pen", "Pencil", "Eraser",
    "Coffee", "Pizza", "Apple", "Cake", "Beer",
    "Sun", "Moon", "Cloud", "CloudRain", "Umbrella",
    "Flame", "Droplet", "Wind", "Snowflake", "Thermometer",
    "Smile", "Frown", "Meh", "ThumbsUp", "ThumbsDown",
    "Check", "X", "Plus", "Minus", "AlertCircle",
    "Info", "HelpCircle", "AlertTriangle", "Shield", "Lock",
    "Unlock", "Key", "Eye", "EyeOff", "Search",
    "Filter", "SlidersHorizontal", "List", "Grid", "Layers",
    "Move", "Copy", "Clipboard", "Repeat", "RotateCw",
    "Maximize", "Minimize", "ZoomIn", "ZoomOut", "Expand",
    "Shrink", "ArrowUp", "ArrowDown", "ArrowLeft", "ArrowRight",
    "ChevronUp", "ChevronDown", "ChevronLeft", "ChevronRight",
    "ChevronsUp", "ChevronsDown", "MoreHorizontal", "MoreVertical",
    "Play", "Pause", "Square", "Circle", "Triangle",
    "Hexagon", "Octagon", "Diamond", "Pentagon", "Hash"
];

export const ICON_CATEGORIES = {
    "Geral": ["Star", "Heart", "Zap", "Target", "Award", "Flag", "Bookmark"],
    "Negócios": ["Briefcase", "TrendingUp", "BarChart", "PieChart", "DollarSign", "CreditCard"],
    "Comunicação": ["Mail", "Phone", "MessageCircle", "Send", "Share", "Bell"],
    "Arquivos": ["File", "Folder", "FileText", "Archive", "Download", "Upload"],
    "Usuários": ["User", "Users", "UserPlus", "UserMinus", "UserCheck"],
    "Tempo": ["Calendar", "Clock", "Timer", "Hourglass", "Watch"],
    "Localização": ["Home", "Building", "MapPin", "Globe", "Navigation"],
    "Compras": ["ShoppingCart", "Package", "Truck", "Store", "Tag"],
    "Tech": ["Code", "Terminal", "Cpu", "Database", "Wifi", "Server"],
    "Mídia": ["Camera", "Image", "Film", "Music", "Headphones"],
    "Ferramentas": ["Settings", "Tool", "Wrench", "Hammer", "Scissors"],
    "Design": ["Palette", "Brush", "Pen", "Pencil", "Layers"],
    "Natureza": ["Sun", "Moon", "Cloud", "Flame", "Droplet", "Wind"],
    "Comida": ["Coffee", "Pizza", "Apple", "Cake", "Beer"],
    "Emoções": ["Smile", "Frown", "ThumbsUp", "ThumbsDown", "Heart"],
    "Ações": ["Check", "X", "Plus", "Minus", "Edit", "Save", "Trash"],
    "Segurança": ["Shield", "Lock", "Unlock", "Key", "Eye", "EyeOff"],
    "Navegação": ["ArrowUp", "ArrowDown", "ArrowLeft", "ArrowRight", "ChevronUp"],
    "Formas": ["Circle", "Square", "Triangle", "Hexagon", "Diamond"]
};
